--- 
document: 
  name: "Manuale di integrazione per servizi basati sul NIS"
  short_name: cie-nis
  description: "Protocollo operativo necessario per utilizzare la Carta di Identità Elettronica 3.0 come strumento per la fruizione di servizi fisici di accesso pinless"
  tags: 
    - CIE
    - NIS
    - Carta di Identità Elettronica
    - Docs Italia
