--- 
document: 
  name: "Manuale operativo per servizi di accesso pinless basati sulla CIE"
  short_name: cie-nis
  description: "Manuale d'uso della Carta d'Identità Elettronica per accesso a servizi fisici senza PIN, come per esempio luoghi di lavoro o zone ad accesso controllato"
  tags: 
    - CIE
    - NIS
    - Carta di Identità Elettronica
    - Docs Italia
