--- 
document: 
  name: "Manuale di integrazione per servizi basati sul NIS"
  short_name: cie-nis
  description: "xxxxx"
  tags: 
    - CIE
    - NIS
    - Carta di Identità Elettronica
    - Docs Italia
